name: checkov
on:
  push
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Run Bridgecrew 
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master
        with:
         api-key: 1d4afaaf-4a41-5946-923e-9756f222f16f
         directory: terraform
